### PR TITLE
feat: create .gitignore file (#24)

### PR DESCRIPTION
**Pull request by ethmtrgt**
**Issue Number:** #24 

**Description of the Changes**
I created a `.gitignore` file using the template from [this URL](https://github.com/github/gitignore/blob/main/Python.gitignore). Please feel free to review it. Thank you so much :slightly_smiling_face:

### CODE REVIEW

**Review by cBridges851 — APPROVED** [review]
Hi @ethmtrgt, thank you for creating this PR and adding a .gitignore! This will be really helpful for when future contributors add to this repo. I'm happy for this to be merged straight in.

For contributions on this repo over Hacktoberfest, I tend to share it on my LinkedIn (https://www.linkedin.com/in/christa-bridges/) as long as the contributor is happy for me to do so. I think this would be a good thing to share as it could provide the opportunity for people to find out what a .gitignore is. Would you be happy for me to share what you've done here, especially since you used a good sense of initiative and made it clear in your PR description where you got the .gitignore from, and have a LinkedIn profile so I can tag you? I could also share your GitHub profile if you like.

Many thanks, and you're more than welcome to contribute again!

**Comment by ethmtrgt** [comment]
Hi @cBridges851, I thank you so much for your words, really appreciate it.

Sure you can share it in your LinkedIn profile but I am not much active on LinkedIn. I would be happy if you can tag my Github profile if possible :)

And many thanks to you again, I am honored!

**Comment by cBridges851** [comment]
Awesome, thanks @ethmtrgt! I'll hopefully get a LinkedIn post out tomorrow, I'll put the post in this thread so you can see what I've put, and I'll definitely tag your GitHub profile :)

Thank you so much, all the best!

**Comment by cBridges851** [comment]
Here's the post @ethmtrgt!  https://www.linkedin.com/posts/christa-bridges_softwareengineering-opensource-hacktoberfest-activity-6991013807678488576-33Jr?utm_source=share&utm_medium=member_android

**Pull request merged**
